"""Typed boundaries — the bottom layer, as this agent sees it.

The harness's contracts (`agent_harness.contracts`), re-exported, beside this
shop's own vocabulary: what a customer can ask for (`Intent`) and the states an
order passes through (`OrderStatus`). Importing this package declares both to
the harness — `Intent` as the intents every route validates against, and the
order-id shape and status grammar of `contracts.reading` as the vocabulary the
harness's checks read — so no route or check runs before they are known.
"""

from agent_harness.contracts import (
    CLAIM_TTL_S,
    ActionDeclined,
    Agentic,
    AlreadyAnswered,
    Approval,
    ApprovalRecords,
    ApprovalRequested,
    Approvals,
    ApprovalState,
    CheckpointStore,
    Claim,
    Clock,
    Completed,
    ConversationId,
    Direct,
    Escalate,
    Escalated,
    Escalation,
    EscalationOutcome,
    Escalations,
    EscalationState,
    Failed,
    IdempotencyKey,
    Identity,
    IntentName,
    LLMClient,
    LocalTool,
    Message,
    MissingIdempotencyKey,
    ModelBudgetExhausted,
    ModelMalformed,
    ModelRefused,
    ModelRequest,
    ModelResponse,
    ModelThrottled,
    ModelUnavailable,
    NeedsApproval,
    Refuse,
    Refused,
    RequestRefused,
    Requests,
    Route,
    RunId,
    Scope,
    SessionStore,
    SideEffectClass,
    StillRunning,
    StoredSession,
    TerminationReason,
    ToolCall,
    ToolClient,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    ToolUnavailable,
    TurnResult,
    Unbindable,
    UnknownTool,
    Usage,
    bind_arguments,
    new_conversation_id,
    new_run_id,
    use_intents,
)
from agent_harness.contracts.reading import use_vocabulary
from support_agent.contracts import reading
from support_agent.contracts.domain import Intent, OrderStatus

use_intents(Intent)
use_vocabulary(reading.VOCABULARY)

__all__ = [
    "ActionDeclined",
    "Agentic",
    "AlreadyAnswered",
    "Approval",
    "ApprovalRecords",
    "ApprovalRequested",
    "Approvals",
    "ApprovalState",
    "bind_arguments",
    "CheckpointStore",
    "Claim",
    "CLAIM_TTL_S",
    "Clock",
    "Completed",
    "ConversationId",
    "Direct",
    "Escalate",
    "Escalated",
    "Escalation",
    "EscalationOutcome",
    "Escalations",
    "EscalationState",
    "Failed",
    "IdempotencyKey",
    "Identity",
    "Intent",
    "IntentName",
    "LLMClient",
    "LocalTool",
    "Message",
    "MissingIdempotencyKey",
    "ModelBudgetExhausted",
    "ModelMalformed",
    "ModelRefused",
    "ModelRequest",
    "ModelResponse",
    "ModelThrottled",
    "ModelUnavailable",
    "NeedsApproval",
    "new_conversation_id",
    "new_run_id",
    "OrderStatus",
    "Refuse",
    "Refused",
    "RequestRefused",
    "Requests",
    "Route",
    "RunId",
    "Scope",
    "SessionStore",
    "SideEffectClass",
    "StillRunning",
    "StoredSession",
    "TerminationReason",
    "ToolCall",
    "ToolClient",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolUnavailable",
    "TurnResult",
    "Unbindable",
    "UnknownTool",
    "Usage",
]
