"""Pin every input to one generation or evaluation run.

A manifest written by hand describes the generation somebody meant to run. This
reads the versions off disk — the catalogs' own package versions, the specs'
declared versions, the commit each repository is at — so the artifact is
evidence rather than intent.

    uv run python scripts/build_manifest.py            # writes BUILD-MANIFEST.md

**What it is for.** G1 regenerates this agent from the specifications alone, N
times, and compares. A divergence is only attributable if both runs were handed
the same inputs, and "the same" has to mean something a machine can check.
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys
from datetime import UTC, datetime

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
SIBLINGS = ROOT.parent
DEST = ROOT / "BUILD-MANIFEST.md"


def commit(repo: pathlib.Path) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        dirty = subprocess.run(
            ["git", "-C", str(repo), "status", "--porcelain"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        return out.stdout.strip() + (" (dirty)" if dirty else "")
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def npm_version(repo: pathlib.Path) -> str:
    path = repo / "package.json"
    return json.loads(path.read_text())["version"] if path.is_file() else "unknown"


def inputs() -> list[tuple[str, str, str, str]]:
    """(artifact, what pins it, version, commit)."""
    profile = yaml.safe_load((ROOT / "harness-profile.yaml").read_text())
    spec_path = ROOT / "worlds" / "clothing.yaml"
    world = yaml.safe_load(spec_path.read_text())
    aoas_path = (spec_path.parent / world["spec"]["path"]).resolve()
    aoas = yaml.safe_load(aoas_path.read_text())

    aac, ahc = SIBLINGS / "ai-assurance-catalog", SIBLINGS / "ai-harness-catalog"
    umbrella, twin = SIBLINGS / "clean-ai-engineering", SIBLINGS / "agenttwin"
    return [
        ("AAC — what must be true", "catalog version", npm_version(aac), commit(aac)),
        ("AHC — what must exist", "catalog version", npm_version(ahc), commit(ahc)),
        ("Baseline", "the umbrella repository", "see BASELINE.md", commit(umbrella)),
        ("Blueprint — A6", "the harness catalog", npm_version(ahc), commit(ahc)),
        ("Pattern library", "the harness catalog", npm_version(ahc), commit(ahc)),
        ("Generation Brief", "assembled, never authored", "not yet assembled", "—"),
        ("AOAS — this agent", "its own declaration", aoas["agent"]["version"], commit(umbrella)),
        ("AWD — the world", "its own declaration", str(world.get("version", "—")), commit(ROOT)),
        (
            "Binding — the harness profile",
            "this repository",
            profile["subject"]["version"],
            commit(ROOT),
        ),
        ("AgentTwin — the runtime", "the sibling repository", "—", commit(twin)),
        ("Generator", "recorded per run, not here", "—", "—"),
    ]


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Build Manifest",
        "",
        "*Generated by `scripts/build_manifest.py`. Never edit by hand — regenerate.*",
        "",
        f"Taken {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
        "Every input to one generation of this agent. A divergence between two",
        "regenerations is only attributable if both were handed the same inputs, and",
        "*the same* has to mean something a machine can check — so this reads versions",
        "and commits off disk rather than describing the run somebody meant to make.",
        "",
        "| Input | Pinned by | Version | Commit |",
        "|---|---|---|---|",
    ]
    lines += [f"| {a} | {b} | {c} | `{d}` |" for a, b, c, d in rows]
    lines += [
        "",
        "**A dirty commit is not a pin.** A row marked `(dirty)` means that input had",
        "uncommitted changes when this was taken, so the generation it describes cannot",
        "be reproduced from the commit alone.",
        "",
        "**The generator is recorded per run.** Model, version and settings belong to",
        "the run that used them, not to the manifest of what was available — G1.1",
        "pre-registers them, and N runs of one spec version differ only in the run.",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    rows = inputs()
    DEST.write_text(render(rows))
    print(f"{DEST}  {len(rows)} inputs pinned")
